# Generated by Django 6.0 on 2025-12-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_varaiation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Varaiation',
            new_name='Variation',
        ),
    ]
